version: "3.8"

services:
  user_service:
    image: user_service
    container_name: user_service
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    env_file:
      - ./user_service/.env
    ports:
      - "8001:8001"
    depends_on:
      - bike_db
    networks:
      - network

  bike_db:
    image: postgres:latest
    container_name: bike_db
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      - DATABASE_HOST=bike_db
      - POSTGRES_DB=bikes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - network
    # volumes:
    #   - /home/nananeko1305/Desktop/postgres:/data/rostgres

networks:
  network:
    driver: bridge
# volumes:
#   user_db:
