version: "3.8"

services:
  user_service:
    image: user_service
    container_name: user_service
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    env_file:
      - ./user_service/.env
    ports:
      - "8001:8001"
    depends_on:
      - user_db
    networks:
      - network

  user_db:
    image: mongo
    container_name: user_db
    restart: on-failure
    networks:
      - network
    volumes:
      - /home/nananeko1305/Desktop/mongoDB:/data/db


networks:
  network:
    driver: bridge

volumes:
  user_db:
